### ISSUE TITLE
sppt does not work with Python2.7

### ISSUE THREAD

**Issue by jpigree** [parkouss/sppt#1]
When installing sppt on a Python 2.7 virtualenv, I get this error:

``` shell
pip install -e . && sppt -o /home/jp/workspace/perso/test
Obtaining file:///home/jp/workspace/perso/sppt
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /home/jp/workspace/virtualenvs/py27/lib/python2.7/site-packages (from sppt==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): colorama in /home/jp/workspace/virtualenvs/py27/lib/python2.7/site-packages (from sppt==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): configobj in /home/jp/workspace/virtualenvs/py27/lib/python2.7/site-packages (from sppt==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /home/jp/workspace/virtualenvs/py27/lib/python2.7/site-packages (from jinja2->sppt==0.1.0)
Requirement already satisfied (use --upgrade to upgrade): six in /home/jp/workspace/virtualenvs/py27/lib/python2.7/site-packages (from configobj->sppt==0.1.0)
Installing collected packages: sppt
  Running setup.py develop for sppt
Successfully installed sppt-0.1.0
in defaults:project_name
before input
Project Name: aa
Traceback (most recent call last):
  File "/home/jp/workspace/virtualenvs/py27/bin/sppt", line 9, in <module>
    load_entry_point('sppt', 'console_scripts', 'sppt')()
  File "/home/jp/workspace/perso/sppt/sppt/main.py", line 93, in main
    ui = variables.vars_to_dict(defaults=get_defaults())
  File "/home/jp/workspace/perso/sppt/sppt/variables.py", line 94, in vars_to_dict
    dct[v.name] = v.value(dct)
  File "/home/jp/workspace/perso/sppt/sppt/variables.py", line 32, in value
    up = input(prompt)
  File "<string>", line 1, in <module>
NameError: name 'aa' is not defined
```

I investigated the issue and it seems to be [your usage of the input built-in](https://github.com/parkouss/sppt/blob/master/sppt/variables.py#L28) which have a different behaviour in 3.x than in 2.7 (https://stackoverflow.com/questions/16457441/nameerror-from-python-input-function).

I would have created a pull request with the fix, but I am actually not sure on how you want to handle it.

Two choices:
- Add a check on Python version and prevent installation when < Python 3
- Handle the thing to keep Python 2 compatibility. Seems that the (ugly) snippet does the trick:

``` python
try:
    input = raw_input
except NameError:
    pass
```

I am ready to create a pull request for this simple fix with your confirmation. :)

**Comment by parkouss** [comment]
Thanks @jpigree for reporting this! I would prefer to support python 2 too, but without doing more hacks than we need to - there is already the library six that handle most of python 2 and 3 differences, https://pythonhosted.org/six/

So we should be able to write the following to support both python versions:

``` python
from six.moves.builtins import input
```

I suspect there may be other issues like that to fix in order to make sppt python2 compatible.

If you find some time to look at that, I'll be happy to merge a PR!

**Comment by jpigree** [comment]
Wow. I did not know this library. Awesome. In the nominal case, I did not encounter any other issues.
I have fixed sppt. But it did not work with six on my dev machine so I used futures instead (http://python-future.org/compatible_idioms.html).

I am creating a PR.

**Comment by parkouss** [comment]
Thanks @jpigree, looks good to me !  I Just merged your PR.
